# Where things are
source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts

# Handling Reading
encoding:     "utf-8"
markdown_ext: "md"

# Serving
baseurl:     /tcdona.github.com

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "posts"
